### ISSUE TITLE
Couldn't find User with id=sign_out (ActiveRecord::RecordNotFound)

### ISSUE THREAD

**Issue by empimp** [RailsApps/rails3-devise-rspec-cucumber#3]
Thanks for a great tutorial!  

After I finished going through it, I was still having rspec and cucumber issues.  I've since tracked down and corrected most of my typos :-)  Unfortunately I've run into two cucumber failures, that appear to me to be related, but I have run out of google (actually duckduckgo,com, google, & stackoverflow) troubleshooting mojo.  _Any troubleshooting guidance would be very much appreciated._

The first error impacts the following three scenarios:
- User signs in successfully with email
- User signs out
- I sign in and edit my account

While the second impacts the, "User signs up with valid data" scenario.

My own troubleshooting has led me to believe that the problem is actually sign_out functionality, specifically as it relates to testing.  One reason I believe this is the commonality between the errors:
`Couldn't find User with id=sign_out (ActiveRecord::RecordNotFound)
      ./app/controllers/users_controller.rb:5:in `show'
      (eval):2:in `click_button'`
The other reason is that I was able to manually replicate these errors until I inserted the missing `:method => 'delete'` statement on the 'Logout' function of app/views/devise/menu/_login_items.html.erb.

I modified my sign_up.feature, but the other feature and step_definition files are unmodified copy/pastes from your repository.

The cucumber error messages, as well as the sign_up.feature, user_controller.rb, and web_steps.rb are available at https://gist.github.com/1066257. 

<script src="https://gist.github.com/1066257.js"> </script>

Thanks, in advance, for any help troubleshooting this problem!

**Comment by Ruby4Life** [comment]
I had the same issue

I noticed that I had java script disabled on my browser!

I enabled JS on my browser

And all is well
