### ISSUE TITLE
`add_route': Invalid route name, already in use: 'root'

### ISSUE THREAD

**Issue by AlexVPopov** [RailsApps/rails3-devise-rspec-cucumber#50]
This code:

```
authenticated :user do
  root :to => 'home#index'
end
root :to => "home#index"
devise_for :users
```

part of section: **Create a Home Controller and View** causes this error:

```
`add_route': Invalid route name, already in use: 'root'
```

When I remove one of the `root :to` lines, the code works. Probably a Rails 4 issue?

**Comment by ashishra0** [comment]
Where exactly is this file located?

**Comment by ashishra0** [comment]
Where is that code file?

**Comment by schadenfred** [comment]
config/routes.rb

**Comment by AlexVPopov** [comment]
As mentioned, there's [a fix](https://github.com/plataformatec/devise/issues/2393#issuecomment-17298414) for this, so I'm closing the issue.
