### ISSUE TITLE
Devise account confirmed message should not say "You are signed in."

### ISSUE THREAD

**Issue by scrawlon** [RailsApps/rails3-devise-rspec-cucumber#51]
in config/locales/devise.en.yml
en:
  devise:
    confirmations:
      confirmed: "Your account was successfully confirmed. You are now signed in."

The latest Devise does not sign users in when they click the confirmation link. 

http://blog.plataformatec.com.br/2013/08/devise-3-1-now-with-more-secure-defaults/

**Comment by DanielKehoe** [comment]
Hmmm thanks for pointing this out for others who may encounter this. I'm no longer supporting this example application. There's a newer version of the example application for Rails 5.0: https://github.com/RailsApps/rails-devise
